### PR TITLE
Support other value types + unquote colors and CSS lengths

### PR DESCRIPTION
**Pull request by VitorLuizC**
- Inject booleans, numbers, null values as literals.
  Parsing
  ```js
  {
    lineHeight: 1.5,
    theme: null,
    responsive: false
  }
  ```
  Inject into SASS
  ```scss
  $lineHeight: 1.5;
  $theme: null;
  $responsive: false
  ```
- Inject Array as SASS-List.
  Parsing
  ```js
  {
    colors: ['red', 'green', 'blue']
  }
  ```
  Inject into SASS
  ```scss
  $colors: (red, green, blue);
  ```
- Inject Object as SASS-Map
  Parsing
  ```js
  {
    font: { family: 'sans-serif', size: '1.6em', color: 'rgb(50, 50, 50)' }
  }
  ```
  Inject into SASS
  ```scss
  $font: ('family': 'sans-serif', size: 1.6em, color: rgb(50, 50, 50));
  ```
- Inject color and length values without quotes
  Parsing
  ```js
  {
    theme: 'rgb(128, 0, 128)',
    maxSize: '1250px'
  }
  ```
  Inject into SASS
  ```scss
  $theme: rgb(128, 0, 128);
  $maxSize: 1250px;
  ```

### CODE REVIEW

**Comment by thaerlabs** [comment]
+1 to merge this

**Comment by VitorLuizC** [comment]
I've maded a module to parse to sass values and there's a way to use it with gulp.

```js
const gulp = require('gulp');
const parse = require('parse-sass-value');
const header = require('gulp-header');
const vars = object => header(
  Object
    .keys(object)
    .map(key => `$${key}: ${parse(object[key])};`)
    .join('\n')
);

gulp.task('build', () => {
  gulp.src('./index.scss')
    .pipe(vars({ theme: 'flat-green' }))
    .pipe(gulp.dest('./'));
});
```

**Comment by pmrotule** [comment]
In the usage example, it shows that the plugin can pass integers but it doesn't. It throws this error `value.match is not a function` since `match()` won't work with numbers:
```js
Object.keys(vars).map((key) => {
  let value = vars[key];
  if ( !value.match(regexp) ) value = `"${value}"`; //<-- ERROR
  sassVars.push(`$${key}: ${value};`);
});
```
+1 to merge this

**Comment by giowe** [comment]
Tnx! sorry for the delay but I'm currently working on other projects and I missed it!

**Pull request merged**
